"""add model filmin.genre

Revision ID: 11d9c7e4df5e
Revises: b83331ff4239
Create Date: 2023-06-27 06:08:56.183993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d9c7e4df5e'
down_revision = 'b83331ff4239'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'filmin_genre',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_filmin_genre')),
        sa.UniqueConstraint('code', name=op.f('uq_filmin_genre_code')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filmin_genre')
    # ### end Alembic commands ###
