"""add model filmin.movie_genre

Revision ID: 3c03a0661222
Revises: d812f9899efb
Create Date: 2023-07-03 08:07:22.598933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c03a0661222'
down_revision = 'd812f9899efb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'filmin_movie_genre',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('movie_id', sa.UUID(), nullable=True),  # type: ignore
        sa.Column('genre_id', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ['genre_id'], ['filmin_genre.code'], name=op.f('fk_filmin_movie_genre_genre_id_filmin_genre')
        ),
        sa.ForeignKeyConstraint(
            ['movie_id'], ['filmin_movie.uuid'], name=op.f('fk_filmin_movie_genre_movie_id_filmin_movie')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_filmin_movie_genre')),
        sa.UniqueConstraint('movie_id', 'genre_id', name='unique_filmin_movie_genre'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filmin_movie_genre')
    # ### end Alembic commands ###
