"""add core models

Revision ID: 440f205f8ac8
Revises:
Create Date: 2023-08-27 06:40:17.009905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440f205f8ac8'
down_revision = None
branch_labels = ('core',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'core_country',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=2), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_core_country')),
        sa.UniqueConstraint('code', name=op.f('uq_core_country_code')),
    )
    op.create_table(
        'core_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', sa.UUID(), nullable=False),  # type: ignore
        sa.Column('first_name', sa.String(length=255), nullable=False),
        sa.Column('last_name', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_core_user')),
        sa.UniqueConstraint('email', name=op.f('uq_core_user_email')),
        sa.UniqueConstraint('uuid', name=op.f('uq_core_user_uuid')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_user')
    op.drop_table('core_country')
    # ### end Alembic commands ###
