"""add model filmin.collection

Revision ID: b83331ff4239
Revises: 4226432f4a20
Create Date: 2023-06-27 04:47:56.336385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83331ff4239'
down_revision = '4226432f4a20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'filmin_collection',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_filmin_collection')),
        sa.UniqueConstraint('uuid', name=op.f('uq_filmin_collection_uuid')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filmin_collection')
    # ### end Alembic commands ###
