"""add model filmin.movie

Revision ID: d812f9899efb
Revises: 11d9c7e4df5e
Create Date: 2023-06-30 14:25:03.793749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd812f9899efb'
down_revision = '11d9c7e4df5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'filmin_movie',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('release_date', sa.Date(), nullable=True),
        sa.Column('budget', sa.BigInteger(), nullable=True),
        sa.Column('revenue', sa.BigInteger(), nullable=True),
        sa.Column('popularity', sa.Float(), nullable=True),
        sa.Column('runtime', sa.BigInteger(), nullable=True),
        sa.Column('rating', sa.Float(), nullable=True),
        sa.Column('original_language', sa.String(length=2), nullable=True),
        sa.Column('collection_id', sa.UUID(), nullable=True),
        sa.Column('overview', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['collection_id'], ['filmin_collection.uuid'], name=op.f('fk_filmin_movie_collection_id_filmin_collection')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_filmin_movie')),
        sa.UniqueConstraint('uuid', name=op.f('uq_filmin_movie_uuid')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filmin_movie')
    # ### end Alembic commands ###
