"""add model core.user

Revision ID: e484f9d6a6af
Revises: 0bfd3f8f6bdf
Create Date: 2023-06-10 07:53:48.208192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e484f9d6a6af'
down_revision = '0bfd3f8f6bdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'core_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', sa.UUID(), nullable=True),
        sa.Column('first_name', sa.String(length=255), nullable=False),
        sa.Column('last_name', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_core_user')),
        sa.UniqueConstraint('email', name=op.f('uq_core_user_email')),
        sa.UniqueConstraint('uuid', name=op.f('uq_core_user_uuid')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_user')
    # ### end Alembic commands ###
